#!/bin/bash
xsetroot -cursor_name left_ptr

# Set resolution and launch polybar
xrandr --output eDP1 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off
bspc monitor eDP1 -d I II III IV V VI VII VIII IX X

# Setup theme
source $HOME/git/dotfiles/themes/forest_night.sh

#========================#
# Autostart applications #
#========================#
$XDG_CONFIG_HOME/polybar/launch.sh
sxhkd & # Manages keybindings
compton -b # Compositor
udiskie -t & # Udiskie, automounts thumb drives
nextcloud & # Nextcloud
caffeine & # Caffeine
nm-applet & # Networkmanager
dunst & # Notification daemon
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & # Graphical authentication agent

#===========================#
# BSPC calls (bspwm config) #
#===========================#
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled
