#! /bin/zsh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off


# Auto launched applications
/home/moritz/.config/polybar/launch.sh &
feh --bg-fill /home/moritz/Nextcloud/linux/backgrounds/radium.jpg &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
udiskie -s &
compton -bf &
nm-applet &
caffeine &
nextcloud &

# Set volume to 0%
pactl set-sink-volume 0 0% &
# Mute on startup (to prevent accidental unmuting)
pactl set-sink-mute 0 1 &
# Mute mic on startup
pactl set-source-mute 1 1 &

