#!/bin/sh


sxhkd &
xsetroot -cursor_name left_ptr
bash $HOME/git/dotfiles/bspwm/configure_screens.sh
bash $HOME/git/dotfiles/scripts/autostart.sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled
