#!/bin/sh

userresources=$HOME/.Xresources
sysresources=/etc/X11/xinit/.Xresources

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

# Start some programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# setxkbmap -layout us_custom
setxkbmap -layout us_custom,de -option grp:caps_toggle

# Read the currently connected screens and write them to ~/.screenlayout/screens
xrandr -q | grep "\ connected" | sed "s/ .*//" > /home/moritz/.screenlayout/screens
# Compares the currently connected screens with pre-defined templates in ~/.screenlayout
xrandr --output VIRTUAL1 --off --output eDP1 --primary --mode 2560x1440 --pos 0x0 --dpi 192 --rotate normal --output DP1 --off --output HDMI2 --off --output HDMI1 --off --output DP2 --off ## Default layout
(cd /home/moritz/.screenlayout && exec find -mindepth 2 -maxdepth 2 -type f -iname screens -execdir bash -c 'cmp --silent ./screens ../screens && ./layout.sh' \;)

# Mute speakers on start. This is a laptop, I don't want noise in lectures
pactl set-sink-mute 0 1

compton -b # Compositor
udiskie -s &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
nextcloud &
nm-applet & # Networkmanager
caffeine &

# Status bar
while true; do
    sh $HOME/git/dotfiles/dwm/status.sh
    sleep 5
done &

~/.fehbg
exec dwm
