#!/bin/sh

userresources=$HOME/.Xresources
sysresources=/etc/X11/xinit/.Xresources
dotfiles=$HOME/git/dotfiles
wallpapers=$HOME/Nextcloud/misc/wallpapers

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

# Start some programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

sh $dotfiles/scripts/configure_screens.sh
sh $dotfiles/scripts/autostart.sh

# Status bar
while true; do
    sh $dotfiles/dwm/status.sh
    sleep 5
done &

# Set background
feh --bg-fill $wallpapers/radium.jpg

# Set keyboard layout
setxkbmap -layout us_custom,de -option grp:caps_toggle

# Host specific configuration
# Hostname 'moritz-arch': mute speakers on start. This is a laptop, I don't want noise in lectures
# Hostname 'moritz-pc-arch': home PC, set to standard volume of 100%, is controlled externally anyways
if [ $(hostname) = 'moritz-arch' ]; then
    pactl set-sink-mute 0 1
    pactl set-sink-volume 0 0
elif [ $(hostname) = 'moritz-pc-arch' ]; then
    pactl set-sink-mute 0 0
    pactl set-sink-volume 0 100%
fi

# Start DWM
sh $dotfiles/X/startdwm.sh
