#!/bin/sh

userresources=$HOME/.Xresources
sysresources=/etc/X11/xinit/.Xresources
dotfiles=$HOME/git/dotfiles
wallpapers=$HOME/Nextcloud/misc/wallpapers

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

# Start some programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Set background
feh --bg-fill $wallpapers/radium.jpg
# Set keyboard layout
setxkbmap -layout us_custom,de -option grp:caps_toggle

# Turn off sound
# This is a laptop, I don't want loud youtube videos blasting in lectures
pactl set-sink-mute 0 1
pactl set-sink-volume 0 0

# Start WM
exec bspwm
