#!/bin/sh
baseurl="https://tagesschau.de"
if [ -z "$1" ]; then
    # Letzte Tagesschau um 20 Uhr
    mpv "$baseurl$(curl https://www.tagesschau.de/multimedia/index.html 2>/dev/null | grep -P 'ts-[\d]{5}\.html">tagesschau</a></h4>' | sed 's/^<h4 class="headline"><a href="//;s/">tagesschau<\/a><\/h4>$//')"
else
    # Letzte Sendung
    mpv "$baseurl$(curl https://www.tagesschau.de/multimedia/index.html 2>/dev/null | grep -P '>Letzte Sendung</a></h4>' -m1 | sed 's/^<h4 class="headline"><a href="//;s/">Letzte Sendung<\/a><\/h4>$//')"
fi
