#!/bin/sh
# Letzte Tagesschau um 20 Uhr
mpv "https://www.tagesschau.de$(curl "https://www.tagesschau.de" 2>/dev/null | grep -oP '(?<=<h4 class="headline"><a href=")\/multimedia\/sendung\/ts-[0-9]*\.html(?=">tagesschau 20 Uhr)')"
