# Folders
ZSH=/usr/share/oh-my-zsh/
ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh

# Environment variables
export EDITOR='vim'
export SSH_KEY_PATH="~/.ssh/rsa_id"


if [[ ! -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi

# Theme
ZSH_THEME="bureau"

DISABLE_AUTO_UPDATE="true"

# Autocorrect of commands
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

# Plugin folder: ~/.oh-my-zsh/plugins/
plugins=(git colored-man-pages lol)

source $ZSH/oh-my-zsh.sh
source /home/moritz/.dotfiles/ZSH/.compinstall

# Aliases
alias ls='ls --color=auto'
alias shutdown='shutdown now'
alias java='java -Dsun.java2d.uiScale=2'
alias spotify='spotify --force-device-scale-factor=1.5'
alias pacaur='pacaur --ignore-ood'
alias jupyter='jupyter notebook'

(cat ~/.cache/wal/sequences &) # Load color scheme generated by wal

if [[ ! -o login ]]; then # Dont run cowsay if it's a login shell
    if [ "wlp4s0: connected to DoctorDickensIndustries" = "$(nmcli | grep 'DoctorDickensIndustries')" ]; then
        cowsay $(fortune -o)
    else
        cowsay $(fortune)
    fi
fi

