# Adds ~/.local/bin to the PATH.
# This allows me to add some functionality to certain executables, such as a better scaling factor for java applications and spotify and different languages for certain applications (e.g. gnucash)
export PATH="/home/moritz/.local/bin:${PATH}"

# Environment variables
export TERM='st'
export GDK_SCALE=1.5
export EDITOR='vim'
export SSH_KEY_PATH="~/.ssh/rsa_id"
export LANG="en_US.UTF-8"
export JUPYTERLAB_DIR=$HOME/.local/share/jupyter/lab
