# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/moritz/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Launch tmux (snippet taken from the arch wiki)
# At "tmux attach || exit", I replaced break with exit so the terminal window closes automatically and I dont have to type exit twice
if which tmux >/dev/null 2>&1; then
    # if no session is started, start a new session
    test -z ${TMUX} && tmux

    # when quitting tmux, try to attach
    while test -z ${TMUX}; do
        tmux attach || exit
    done
fi